disable-version-string: true
resolve-type-alias: false
with-expecter: true
mock-build-tags: "!compile"
inpackage: true
issue-845-fix: true
filename: "{{.InterfaceName | snakecase }}_mock.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
packages:
  github.com/ksysoev/readmee/pkg/ssh:
    interfaces:
      Service:
  github.com/ksysoev/readmee/pkg/core:
    interfaces:
      userRepo:
      someAPIProv:
  github.com/ksysoev/readmee/pkg/repo/user:
    interfaces:
      userDAO: 
